### PR TITLE
Porposal add option comment

### PR DESCRIPTION
**Pull request by zabojcaspamu**
Add option check to display

### CODE REVIEW

**Comment by thehunmonkgroup** [comment]
The code change seems pretty straightforward, couple of clarifying questions. 

1. Can you describe a valid use case for this feature?
2. Can you provide a more clear description of the feature in the command line help?

**Comment by zabojcaspamu** [comment]
1. Comment is very useful in monitoring system (Nagiosm Thruk, Icinga). for example "No new file upload via ftp"
2. Comment display in monitoring system

**Comment by thehunmonkgroup** [comment]
Another question: how will this feature impact the ability to add performance data to the return value?

**Comment by zabojcaspamu** [comment]
This comment is added to end of string. After text about error/OK. I thing is no impact.

**Comment by thehunmonkgroup** [comment]
Would it be better to only add the comment if the plugin returned a success state, or should it be added to the output no matter return state?

Also, could you add ```comment=``` to the list of default variables?

**Comment by zabojcaspamu** [comment]
Hmm, I thing that should be added if state is error or warning. nagios show comment (command, link to wiki or somethink). No matter state is OK too.

Default value comment is empty

**Comment by thehunmonkgroup** [comment]
I understand that the default value of a Bash variable is empty, but I want it declared explicitly like the other variables are -- this helps code clarity.

Also, I'd don't like ```-k``` as the the argument switch -- can you please make it ```--comment```?

The help description still needs to be changed to something more understandable -- I think ```Comment to append to plugin output``` would be more clear than your original suggestion, thoughts?

**Comment by thehunmonkgroup** [comment]
We're almost there, still need to update the help description for this feature so that it's usage is more clear.

I propose changing it to ```Comment to append to plugin output``` -- can you add this or a similar enhancement to the PR? Should be good for merge after that.

**Comment by zabojcaspamu** [comment]
I added this discription

**Comment by thehunmonkgroup** [comment]
Merged PR with some minor adjustments.

Thanks for your work on this, it's always nice when somebody is willing to put in some work to contribute to a project -- that's how open source is supposed to work!

**Pull request closed without merging**
