### PR TITLE
Bugfix: correctly check files with space in its filename

### PR DESCRIPTION
**Pull request by sircubbi**
This plugin does not correctly check files with have spaces in the filename. To properly iterate over the filelist make sure that only newlines are used as separator.

### CODE REVIEW

**Comment by sircubbi** [comment]
Thanks for the input.
I agree that fiddling with IFS on a global-scope could be harmful. Your suggestion looks fine for me. It is a little bit obscure, but as long as it does the trick I guess its ok.

**Comment by thehunmonkgroup** [comment]
> It is a little bit obscure

Yes, I agree. Do you have a suggestion that is POSIX-compliant, properly scoped, and reads better?

**Comment by sircubbi** [comment]
Not really, sorry. I always find it hard to properly write compliant shellscripts. So I guess your solution is the way to go.

**Comment by thehunmonkgroup** [comment]
Pushed my fix, please test and let me know how it works for you.

**Pull request closed without merging**
